########################################################################
# Copyright (c) 1988-2017 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 10/13/2017
#
# generic Gcc Makefile for porta Library libporta
########################################################################


#
# target
#
libporta_LIBTARGET = libporta.${LIBEXT}

########################################################################

#
# user c++ flags
#
libporta_USRCXXFLAGS += \
${porta_USRCXXFLAGS} \

#
# user defines
#
libporta_USRDEFINES += \
${porta_USRDEFINES} \

#
# user includes
#
libporta_USRINCLUDES += \
${porta_USRINCLUDES} \

#
# user libdirs
#
libporta_USRLIBDIRS += \
${porta_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
#libporta_LIB_C_SOURCES += \
#${PORTA_SRC}/porta/base/Base.c \

#
# Library .cc sources
#
#libporta_LIB_CC_SOURCES += \
#${PORTA_SRC}/porta/base/Base.cc \

#
# Library .cxx sources
#
#libporta_LIB_CXX_SOURCES += \
#${PORTA_SRC}/porta/base/Base.cxx \

#
# Library .cpp sources
#
libporta_LIB_CPP_SOURCES += \
${NADIR_SRC}/xos/base/Base.cpp \

#
# Library .m sources
#
#libporta_LIB_M_SOURCES += \
#${PORTA_SRC}/porta/base/Base.m \

#
# Library .mm sources
#
#libporta_LIB_MM_SOURCES += \
#${PORTA_SRC}/porta/base/Base.mm \


########################################################################




