///////////////////////////////////////////////////////////////////////
/// Copyright (c) 1988-2019 $organization$
///
/// This software is provided by the author and contributors ``as is'' 
/// and any express or implied warranties, including, but not limited to, 
/// the implied warranties of merchantability and fitness for a particular 
/// purpose are disclaimed. In no event shall the author or contributors 
/// be liable for any direct, indirect, incidental, special, exemplary, 
/// or consequential damages (including, but not limited to, procurement 
/// of substitute goods or services; loss of use, data, or profits; or 
/// business interruption) however caused and on any theory of liability, 
/// whether in contract, strict liability, or tort (including negligence 
/// or otherwise) arising in any way out of the use of this software, 
/// even if advised of the possibility of such damage.
///
///   File: Which.hpp
///
/// Author: $author$
///   Date: 1/2/2019
///////////////////////////////////////////////////////////////////////
#ifndef _PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_WHICH_HPP
#define _PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_WHICH_HPP

#include "porta/base/Base.hpp"

#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_GATEWAY_INTERFACE "GATEWAY_INTERFACE"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_NAME "SERVER_NAME"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_PORT "SERVER_PORT"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_PROTOCOL "SERVER_PROTOCOL"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_SOFTWARE "SERVER_SOFTWARE"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_AUTH_TYPE "AUTH_TYPE"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_CONTENT_FILE "CONTENT_FILE"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_CONTENT_LENGTH "CONTENT_LENGTH"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_CONTENT_TYPE "CONTENT_TYPE"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_OUTPUT_FILE "OUTPUT_FILE"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_PATH_INFO "PATH_INFO"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_PATH_TRANSLATED "PATH_TRANSLATED"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_QUERY_STRING "QUERY_STRING"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_ADDR "REMOTE_ADDR"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_USER "REMOTE_USER"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REQUEST_LINE "REQUEST_LINE"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REQUEST_METHOD "REQUEST_METHOD"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_HOST "REMOTE_HOST"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_IDENT "REMOTE_IDENT"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_HTTP_ACCEPT "HTTP_ACCEPT"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_HTTP_USER_AGENT "HTTP_USER_AGENT"
#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SCRIPT_NAME "SCRIPT_NAME"

#define PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAMES \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_GATEWAY_INTERFACE, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_NAME, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_PORT, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_PROTOCOL, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SERVER_SOFTWARE, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_AUTH_TYPE, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_CONTENT_FILE, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_CONTENT_LENGTH, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_CONTENT_TYPE, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_OUTPUT_FILE, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_PATH_INFO, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_PATH_TRANSLATED, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_QUERY_STRING, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_ADDR, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_USER, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REQUEST_LINE, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REQUEST_METHOD, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_HOST, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_REMOTE_IDENT, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_HTTP_ACCEPT, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_HTTP_USER_AGENT, \
    PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_NAME_SCRIPT_NAME,

namespace porta {
namespace protocol {
namespace http {
namespace cgi {
namespace environment {
namespace variable {

///////////////////////////////////////////////////////////////////////
///  Enum: Which
///////////////////////////////////////////////////////////////////////
typedef int Which;
enum {
    None = 0,

    GATEWAY_INTERFACE,
    SERVER_NAME,
    SERVER_PORT,
    SERVER_PROTOCOL,
    SERVER_SOFTWARE,
    AUTH_TYPE,
    CONTENT_FILE,
    CONTENT_LENGTH,
    CONTENT_TYPE,
    OUTPUT_FILE,
    PATH_INFO,
    PATH_TRANSLATED,
    QUERY_STRING,
    REMOTE_ADDR,
    REMOTE_USER,
    REQUEST_LINE,
    REQUEST_METHOD,
    REMOTE_HOST,
    REMOTE_IDENT,
    HTTP_ACCEPT,
    HTTP_USER_AGENT,
    SCRIPT_NAME,

    Next,
    First = (None + 1),
    Last = (Next - 1),
    Count = ((Last - First) + 1)
};

} // namespace variable
} // namespace environment 
} // namespace cgi 
} // namespace http 
} // namespace protocol 
} // namespace porta 

#endif // _PORTA_PROTOCOL_HTTP_CGI_ENVIRONMENT_VARIABLE_WHICH_HPP 
